In [7]:
import pandas as pd

In [12]:
df = pd.read_csv("normalized_18.csv")

ParserError: Error tokenizing data. C error: Expected 20 fields in line 4, saw 26

In [ ]:
df = pd.read_csv("listfilmjpbox.csv", sep=';', on_bad_lines='skip')

In [9]:
import pandas as pd
import numpy as np

# Définir l'ordre de colonnes souhaité (18 colonnes)
desired_columns = [
    "Titre",
    "URL",
    "Entrées 1ère semaine",
    "Entrées totales",
    "Réalisateur",
    "Producteur",            # Colonne à ajouter
    "Pays",
    "Genre",
    "Date de sortie",
    "Classification",
    "Distributeur",
    "Rang toutes exploitations",
    "Rang général",
    "Rang 2008",
    "Nb 1ère places hebdo",
    "Nb semaines Top20",
    "Meilleure place hebdo",
    "Acteurs"
]

# Charger le fichier CSV qui contient des lignes à 17 colonnes (sans la colonne "Producteur")
df = pd.read_csv('invalid_17.csv')

# Ajouter la colonne manquante "Producteur" avec la valeur NaN
df['Producteur'] = np.nan

# Réordonner les colonnes selon l'ordre souhaité
df = df[desired_columns]

# Enregistrer le DataFrame normalisé dans un nouveau fichier CSV
df.to_csv('normalized_18.csv', index=False)

print("Le fichier 'normalized_18.csv' a été créé avec la structure souhaitée.")

KeyError: "['Titre', 'URL', 'Entrées 1ère semaine', 'Entrées totales', 'Réalisateur', 'Pays', 'Genre', 'Date de sortie', 'Classification', 'Distributeur', 'Rang toutes exploitations', 'Rang général', 'Rang 2008', 'Nb 1ère places hebdo', 'Nb semaines Top20', 'Meilleure place hebdo', 'Acteurs'] not in index"

In [10]:
import pandas as pd
import numpy as np

# Définir les noms de colonnes pour le CSV initial
columns_17 = [
    "Titre",
    "URL",
    "Entrées 1ère semaine",
    "Entrées totales",
    "Réalisateur",
    "Pays",
    "Genre",
    "Date de sortie",
    "Classification",
    "Distributeur",
    "Rang toutes exploitations",
    "Rang général",
    "Rang 2008",
    "Nb 1ère places hebdo",
    "Nb semaines Top20",
    "Meilleure place hebdo",
    "Acteurs"
]

# Charger le fichier CSV sans en-tête et lui attribuer les noms de colonnes définies
df = pd.read_csv('invalid_17.csv', header=None, names=columns_17)

# Ajouter la colonne manquante "Producteur" avec la valeur NaN
df['Producteur'] = np.nan

# Spécifier l'ordre final des colonnes (18 colonnes)
desired_columns = [
    "Titre",
    "URL",
    "Entrées 1ère semaine",
    "Entrées totales",
    "Réalisateur",
    "Producteur",  # Nouvelle colonne ajoutée
    "Pays",
    "Genre",
    "Date de sortie",
    "Classification",
    "Distributeur",
    "Rang toutes exploitations",
    "Rang général",
    "Rang 2008",
    "Nb 1ère places hebdo",
    "Nb semaines Top20",
    "Meilleure place hebdo",
    "Acteurs"
]

# Réordonner le DataFrame
df = df[desired_columns]

# Sauvegarder le DataFrame normalisé dans un nouveau fichier CSV
df.to_csv('normalized_18.csv', index=False)

print("Le fichier 'normalized_18.csv' a été créé avec la structure souhaitée.")

Le fichier 'normalized_18.csv' a été créé avec la structure souhaitée.

In [11]:
import pandas as pd
import numpy as np

# Définir les noms de colonnes pour le CSV initial à 17 colonnes (sans "Producteur")
columns_17 = [
    "Titre",
    "URL",
    "Entrées 1ère semaine",
    "Entrées totales",
    "Réalisateur",
    "Pays",
    "Genre",
    "Date de sortie",
    "Classification",
    "Distributeur",
    "Rang toutes exploitations",
    "Rang général",
    "Rang 2008",
    "Nb 1ère places hebdo",
    "Nb semaines Top20",
    "Meilleure place hebdo",
    "Acteurs"
]

# Charger le fichier invalid_17.csv sans en-tête et définir ses colonnes
df = pd.read_csv('invalid_17.csv', header=None, names=columns_17)

# Ajouter la colonne manquante "Producteur"
if 'Producteur' not in df.columns:
    df['Producteur'] = np.nan  # Ajouter et remplir par "NaN"

# Réordonner les colonnes pour obtenir la structure souhaitée avec 18 colonnes
desired_columns = [
    "Titre",
    "URL",
    "Entrées 1ère semaine",
    "Entrées totales",
    "Réalisateur",
    "Producteur",  # Colonne ajoutée et/ou complétée par NaN
    "Pays",
    "Genre",
    "Date de sortie",
    "Classification",
    "Distributeur",
    "Rang toutes exploitations",
    "Rang général",
    "Rang 2008",
    "Nb 1ère places hebdo",
    "Nb semaines Top20",
    "Meilleure place hebdo",
    "Acteurs"
]

# Réorganiser le DataFrame dans l'ordre désiré
df = df[desired_columns]

# Sauvegarder le DataFrame modifié dans un fichier CSV final
df.to_csv('normalized_18.csv', index=False)

print("Les données ont été normalisées. Le fichier 'normalized_18.csv' est prêt avec la colonne Producteur remplie par NaN si absente.")

Les données ont été normalisées. Le fichier 'normalized_18.csv' est prêt avec la colonne Producteur remplie par NaN si absente.

In [13]:
import pandas as pd
import numpy as np

# Définir les noms de colonnes pour le CSV initial à 17 colonnes (sans "Producteur")
columns_17 = [
    "Titre",
    "URL",
    "Entrées 1ère semaine",
    "Entrées totales",
    "Réalisateur",
    "Pays",
    "Genre",
    "Date de sortie",
    "Classification",
    "Distributeur",
    "Rang toutes exploitations",
    "Rang général",
    "Rang 2008",
    "Nb 1ère places hebdo",
    "Nb semaines Top20",
    "Meilleure place hebdo",
    "Acteurs"
]

# Charger le fichier invalid_17.csv sans en-tête et définir ses colonnes
df = pd.read_csv('invalid_17.csv', header=None, names=columns_17)

# Ajouter la colonne manquante "Producteur" et la remplir par NaN
df['Producteur'] = np.nan

# Normaliser les colonnes problématiques : remplissage des champs vides ou incohérents avec NaN
df = df.applymap(lambda x: np.nan if pd.isna(x) or (isinstance(x, str) and not x.strip()) else x)

# Réordonner les colonnes pour obtenir la structure souhaitée avec 18 colonnes
desired_columns = [
    "Titre",
    "URL",
    "Entrées 1ère semaine",
    "Entrées totales",
    "Réalisateur",
    "Producteur",  # Nouvelle colonne ajoutée
    "Pays",
    "Genre",
    "Date de sortie",
    "Classification",
    "Distributeur",
    "Rang toutes exploitations",
    "Rang général",
    "Rang 2008",
    "Nb 1ère places hebdo",
    "Nb semaines Top20",
    "Meilleure place hebdo",
    "Acteurs"
]

df = df[desired_columns]

# Sauvegarder le DataFrame modifié dans un fichier CSV final
df.to_csv('normalized_18.csv', index=False)

print("Les données ont été normalisées avec succès et sauvegardées dans 'normalized_18.csv'.")

Les données ont été normalisées avec succès et sauvegardées dans 'normalized_18.csv'.

/tmp/ipykernel_580433/4241725569.py:32: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: np.nan if pd.isna(x) or (isinstance(x, str) and not x.strip()) else x)

In [14]:
import pandas as pd

# Charger le fichier CSV
df = pd.read_csv('normalized_18.csv')

# Afficher les premières lignes du DataFrame
print(df.head())

ParserError: Error tokenizing data. C error: Expected 20 fields in line 4, saw 26

In [15]:
with open('normalized_18.csv', 'r') as file:
    for i, line in enumerate(file):
        fields_count = len(line.split(','))
        if fields_count != 18:  # Vérifiez si le nombre de colonnes est incorrect
            print(f"Ligne {i + 1}: {fields_count} champs trouvés\n{line}")

Ligne 2: 20 champs trouvés
Scream 4                                                 , https://www.jpbox-office.com/fichfilm.php?id=11277&view=2, -                   , 1 070 890      , Wes Craven                  ,           , Etats-Unis      , Horreur           , 13/04/2011    , Moins de 12 ans                                        , SND                        , 3 754                    , 3 782       ,          ,                    0,                 5, 2                    , "[{""name"": ""Courteney Cox"", ""role_type"": ""Second rôle"", ""character"": ""Gale Weathers-Riley""}]"

Ligne 3: 20 champs trouvés
Resident Evil                                            , https://www.jpbox-office.com/fichfilm.php?id=1779&view=2 , -                   , 1 105 943      , Paul W.S. Anderson          ,           , Etats-Unis      , Aventure - Action , 03/04/2002    , Moins de 12 ans                                        , Metropolitan               , 3 641                    , 3 670       ,          ,                    0,                 5, 2                    , "[{""name"": ""Milla Jovovich"", ""role_type"": ""Rôle principal"", ""character"": ""Alice""}]"

Ligne 4: 26 champs trouvés
Mariages!                                                , https://www.jpbox-office.com/fichfilm.php?id=1065&view=2 , -                   , 2 008 899      ,                             ,           , France          , Comédie           , 21/04/2004    , Distribué par Pan-Européenne                           , Pan-Européenne             , 1 743                    , 1 757       ,          ,                    1,                 7, 1                    , "[{""name"": ""Jean Dujardin"", ""role_type"": ""Rôle principal"", ""character"": ""Alex""}, {""name"": ""Mathilde Seigner"", ""role_type"": ""Rôle principal"", ""character"": ""Valentine""}, {""name"": ""Miou-Miou"", ""role_type"": ""Second rôle"", ""character"": ""Gabrielle""}]"

Ligne 5: 20 champs trouvés
Gainsbourg - (vie héroïque)                              , https://www.jpbox-office.com/fichfilm.php?id=10989&view=2, -                   , 1 199 451      ,                             ,           , France          , Comédie dramatique, 20/01/2010    , Tous publics                                           , Universal                  , 3 331                    , 3 359       ,          ,                    0,                 5, 3                    , "[{""name"": ""Yolande Moreau"", ""role_type"": ""Second rôle"", ""character"": ""Fréhel""}]"

Ligne 6: 29 champs trouvés
L'Homme qui murmurait à l'oreille des chevaux            , https://www.jpbox-office.com/fichfilm.php?id=3050&view=2 , -                   , 2 997 201      , Robert Redford              ,           , Etats-Unis      , Romance           , 02/09/1998    , Tous publics                                           , GBVI                       , 869                      , 871         ,          ,                    2,                 9, 1                    , "[{""name"": ""Robert Redford"", ""role_type"": ""Rôle principal"", ""character"": """"}, {""name"": ""Kristin Scott Thomas"", ""role_type"": ""Rôle principal"", ""character"": ""Annie MacLean""}, {""name"": ""Scarlett Johansson"", ""role_type"": ""Second rôle"", ""character"": """"}, {""name"": ""Sam Neill"", ""role_type"": """", ""character"": """"}]"

Ligne 7: 23 champs trouvés
La Fin des temps                                         , https://www.jpbox-office.com/fichfilm.php?id=2732&view=2 , -                   , 1 298 541      , Peter Hyams                 ,           , Etats-Unis      , Aventure - Action , 15/12/1999    , Moins de 12 ans                                        , Metropolitan               , 3 038                    , 3 063       ,          ,                    0,                 6, 2                    , "[{""name"": ""Arnold Schwarzenegger"", ""role_type"": ""Rôle principal"", ""character"": """"}, {""name"": ""Gabriel Byrne"", ""role_type"": """", ""character"": """"}]"

Ligne 8: 26 champs trouvés
De Gaulle                                                , https://www.jpbox-office.com/fichfilm.php?id=20121&view=2, 60 908              , 859 981        ,                             ,           , France          , Drame             , 04/03/2020    , Distribué par SND                                      , SND                        , 4 522                    , 4 559       ,          ,                    0,                 7, 2                    , "[{""name"": ""Isabelle Carré"", ""role_type"": ""Rôle principal"", ""character"": ""Yvonne de Gaulle""}, {""name"": ""Lambert Wilson"", ""role_type"": ""Rôle principal"", ""character"": ""Charles de Gaulle""}, {""name"": ""Oliver Gourmet"", ""role_type"": ""Second rôle"", ""character"": ""Paul Reynaud""}]"

Ligne 9: 29 champs trouvés
Matrix Resurrections                                     , https://www.jpbox-office.com/fichfilm.php?id=19943&view=2, 50 587              , 972 644        , Wachowski (brothers)        ,           , Etats-Unis      , Science Fiction   , 22/12/2021    , Tous publics                                           , Warner Bros.               , 4 112                    , 4 148       ,          ,                    0,                 5, 3                    , "[{""name"": ""Carrie-Anne Moss"", ""role_type"": ""Rôle principal"", ""character"": ""Trinity""}, {""name"": ""Keanu Reeves"", ""role_type"": ""Rôle principal"", ""character"": ""Neo""}, {""name"": ""Lambert Wilson"", ""role_type"": ""Second rôle"", ""character"": ""Le Mérovingien""}, {""name"": ""Christina Ricci"", ""role_type"": ""Apparition"", ""character"": ""Gwyn de Vere""}]"

Ligne 10: 26 champs trouvés
Casse-tête chinois                                       , https://www.jpbox-office.com/fichfilm.php?id=13229&view=2, -                   , 1 536 489      , Cédric Klapisch             ,           , France          , Comédie           , 04/12/2013    , Tous publics                                           , Studiocanal                , 2 502                    , 2 523       ,          ,                    0,                 6, 3                    , "[{""name"": ""Cécile De France"", ""role_type"": ""Rôle principal"", ""character"": ""Isabelle""}, {""name"": ""Romain Duris"", ""role_type"": ""Rôle principal"", ""character"": ""Xavier""}, {""name"": ""Audrey Tautou"", ""role_type"": ""Rôle principal"", ""character"": ""Martine""}]"

Ligne 11: 29 champs trouvés
Forrest Gump                                             , https://www.jpbox-office.com/fichfilm.php?id=4249&view=2 , -                   , 3 963 919      , Robert Zemeckis             ,           , Etats-Unis      , Comédie           , 05/10/1994    , Tous publics                                           , UIP                        , 471                      , 465         ,          ,                    1,                13, 1                    , "[{""name"": ""Tom Hanks"", ""role_type"": ""Rôle principal"", ""character"": ""Forrest Gump""}, {""name"": ""Robin Wright"", ""role_type"": ""Rôle principal"", ""character"": """"}, {""name"": ""Gary Sinise"", ""role_type"": ""Second rôle"", ""character"": """"}, {""name"": ""Sally Field"", ""role_type"": """", ""character"": """"}]"

Ligne 12: 20 champs trouvés
La Vengeance d'une blonde                                , https://www.jpbox-office.com/fichfilm.php?id=4256&view=2 , -                   , 2 039 370      ,                             ,           , France          , Comédie           , 26/01/1994    , Distribué par AMLF                                     , AMLF                       , 1 711                    , 1 725       ,          ,                    1,                 6, 1                    , "[{""name"": ""Christian Clavier"", ""role_type"": ""Rôle principal"", ""character"": ""Gérard Bréha""}]"

Ligne 13: 32 champs trouvés
La Nuit au musée : Le Secret des Pharaons                , https://www.jpbox-office.com/fichfilm.php?id=14004&view=2, -                   , 1 576 649      , Shawn Levy                  ,           , Etats-Unis      , Film familial     , 04/02/2015    , Tous publics                                           , 20th Century Fox           , 2 430                    , 2 451       ,          ,                    0,                 5, 2                    , "[{""name"": ""Ben Stiller"", ""role_type"": ""Rôle principal"", ""character"": ""Larry Daley / Laa""}, {""name"": ""Robin Williams"", ""role_type"": ""Second rôle"", ""character"": ""Theodore Roosevelt""}, {""name"": ""Owen Wilson"", ""role_type"": ""Second rôle"", ""character"": ""Jedidiah""}, {""name"": ""Rebel Wilson"", ""role_type"": ""Second rôle"", ""character"": ""Tilly""}, {""name"": ""Hugh Jackman"", ""role_type"": ""Apparition"", ""character"": ""Le Roi Arthur""}]"

Ligne 14: 29 champs trouvés
Boudu                                                    , https://www.jpbox-office.com/fichfilm.php?id=738&view=2  , -                   , 1 199 369      , Gérard Jugnot               ,           , France          , Comédie           , 09/03/2005    , Distribué par Pathé                                    , Pathé                      , 3 332                    , 3 360       ,          ,                    1,                 5, 1                    , "[{""name"": ""Gérard Depardieu"", ""role_type"": ""Rôle principal"", ""character"": ""Boudu""}, {""name"": ""Catherine Frot"", ""role_type"": ""Rôle principal"", ""character"": """"}, {""name"": ""Gérard Jugnot"", ""role_type"": ""Rôle principal"", ""character"": ""Christian Lespinglet""}, {""name"": ""Jean-Paul Rouve"", ""role_type"": ""Second rôle"", ""character"": """"}]"

Ligne 15: 35 champs trouvés
J'accuse                                                 , https://www.jpbox-office.com/fichfilm.php?id=18775&view=2, 10 268              , 1 567 306      , Roman Polanski              ,           , France          , Drame             , 13/11/2019    , Tous publics                                           , Gaumont                    , 2 445                    , 2 466       ,          ,                    1,                 6, 1                    , "[{""name"": ""Jean Dujardin"", ""role_type"": ""Rôle principal"", ""character"": ""Colonel Georges Picquart""}, {""name"": ""Emmanuelle Seigner"", ""role_type"": ""Rôle principal"", ""character"": ""Pauline Monnier""}, {""name"": ""Mathieu Amalric"", ""role_type"": ""Second rôle"", ""character"": ""Bertillon""}, {""name"": ""Vincent Perez"", ""role_type"": ""Second rôle"", ""character"": ""Maître Leblois""}, {""name"": ""Denis Podalydès"", ""role_type"": ""Second rôle"", ""character"": ""Maître Demange""}, {""name"": ""Melvil Poupaud"", ""role_type"": ""Second rôle"", ""character"": ""Maitre Labori""}]"

Ligne 16: 20 champs trouvés
Tigre et dragon                                          , https://www.jpbox-office.com/fichfilm.php?id=2421&view=2 , -                   , 1 806 197      , Ang Lee                     ,           , Chine           , Aventure - Action , 04/10/2000    , Tous publics                                           , Warner Bros.               , 2 041                    , 2 059       ,          ,                    0,                 6, 2                    , "[{""name"": ""Yun-Fat Chow"", ""role_type"": ""Rôle principal"", ""character"": ""Li Mu Bai""}]"

Ligne 17: 23 champs trouvés
Les Femmes du 6e étage                                   , https://www.jpbox-office.com/fichfilm.php?id=11814&view=2, -                   , 2 213 187      ,                             ,           , France          , Comédie           , 16/02/2011    , Tous publics                                           , SND                        , 1 508                    , 1 520       ,          ,                    0,                 9, 3                    , "[{""name"": ""Sandrine Kiberlain"", ""role_type"": ""Rôle principal"", ""character"": ""Suzanne Joubert""}, {""name"": ""Fabrice Luchini"", ""role_type"": ""Rôle principal"", ""character"": ""Jean-Louis Joubert""}]"

Ligne 18: 23 champs trouvés
Speed 2                                                  , https://www.jpbox-office.com/fichfilm.php?id=3395&view=2 , -                   , 1 134 913      , Jan De Bont                 ,           , Etats-Unis      , Aventure - Action , 23/07/1997    , Tous publics                                           , UFD                        , 3 549                    , 3 579       ,          ,                    2,                 5, 1                    , "[{""name"": ""Sandra Bullock"", ""role_type"": ""Rôle principal"", ""character"": ""Annie Porter""}, {""name"": ""Willem Dafoe"", ""role_type"": ""Rôle principal"", ""character"": """"}]"

Ligne 19: 23 champs trouvés
Sully                                                    , https://www.jpbox-office.com/fichfilm.php?id=15635&view=2, 14 345              , 1 178 535      , Clint Eastwood              ,           , Etats-Unis      , Drame             , 30/11/2016    , Tous publics                                           , Warner Bros.               , 3 397                    , 3 425       ,          ,                    0,                 5, 3                    , "[{""name"": ""Tom Hanks"", ""role_type"": ""Rôle principal"", ""character"": ""Chesley 'Sully' Sullenberger""}, {""name"": ""Aaron Eckhart"", ""role_type"": ""Second rôle"", ""character"": ""Jeff Skiles""}]"

Ligne 20: 26 champs trouvés
Ali                                                      , https://www.jpbox-office.com/fichfilm.php?id=2119&view=2 , -                   , 1 035 360      , Michael Mann                ,           , Etats-Unis      , Drame             , 27/02/2002    , Distribué par Bac Films                                , Bac Films                  , 3 876                    , 3 906       ,          ,                    0,                 5, 2                    , "[{""name"": ""Will Smith"", ""role_type"": ""Rôle principal"", ""character"": ""Muhammad Ali""}, {""name"": ""Jamie Foxx"", ""role_type"": ""Rôle principal"", ""character"": ""Drew 'Bundini' Brown""}, {""name"": ""Jon Voight"", ""role_type"": ""Second rôle"", ""character"": ""Howard Cosell""}]"

Ligne 21: 24 champs trouvés
"Tanguy, le retour"                                      , https://www.jpbox-office.com/fichfilm.php?id=18821&view=2, 30 252              , 1 027 447      , Etienne Chatiliez           ,           , France          , Comédie           , 10/04/2019    , Tous publics                                           , SND                        , 3 902                    , 3 932       ,          ,                    1,                 6, 1                    , "[{""name"": ""Sabine Azéma"", ""role_type"": ""Rôle principal"", ""character"": ""Edith""}, {""name"": ""André Dussollier"", ""role_type"": ""Rôle principal"", ""character"": ""Paul""}]"

Ligne 22: 23 champs trouvés
Made in America                                          , https://www.jpbox-office.com/fichfilm.php?id=4549&view=2 , -                   , 1 175 469      ,                             ,           , Etats-Unis      , Comédie           , 23/06/1993    , Distribué par Warner Bros.                             , Warner Bros.               , 3 409                    , 3 437       ,          ,                    2,                 4, 1                    , "[{""name"": ""Will Smith"", ""role_type"": ""Rôle principal"", ""character"": ""Tea Cake Walters""}, {""name"": ""Whoopi Goldberg"", ""role_type"": ""Rôle principal"", ""character"": """"}]"

Ligne 23: 20 champs trouvés
Alvin et les Chipmunks - A fond la caisse                , https://www.jpbox-office.com/fichfilm.php?id=15195&view=2, -                   , 1 799 931      ,                             ,           , Etats-Unis      , Film familial     , 03/02/2016    , Tous publics                                           , 20th Century Fox           , 2 051                    , 2 069       ,          ,                    0,                 5, 3                    , "[{""name"": ""Anna Faris"", ""role_type"": ""Voix"", ""character"": ""off - Jeanette Miller""}]"

Ligne 24: 29 champs trouvés
Tout pour plaire                                         , https://www.jpbox-office.com/fichfilm.php?id=726&view=2  , -                   , 1 445 384      ,                             ,           , France          , Comédie           , 16/03/2005    , Distribué par Diaphana                                 , Diaphana                   , 2 700                    , 2 725       ,          ,                    0,                 7, 2                    , "[{""name"": ""Judith Godrèche"", ""role_type"": ""Rôle principal"", ""character"": ""Marie""}, {""name"": ""Mathilde Seigner"", ""role_type"": ""Rôle principal"", ""character"": """"}, {""name"": ""Pascal Elbé"", ""role_type"": ""Second rôle"", ""character"": ""Simon Devos""}, {""name"": ""François-Xavier Demaison"", ""role_type"": ""Apparition"", ""character"": ""L'agent immobilier""}]"

Ligne 25: 20 champs trouvés
Mauvais esprit                                           , https://www.jpbox-office.com/fichfilm.php?id=1441&view=2 , -                   , 1 106 439      ,                             ,           , France          , Comédie           , 05/11/2003    , Tous publics                                           , Pathé                      , 3 638                    , 3 667       ,          ,                    0,                 5, 3                    , "[{""name"": ""Thierry Lhermitte"", ""role_type"": ""Rôle principal"", ""character"": """"}]"

Ligne 26: 20 champs trouvés
Jack Reacher 2                                           , https://www.jpbox-office.com/fichfilm.php?id=15627&view=2, -                   , 926 882        , Edward Zwick                ,           , Etats-Unis      , Thriller          , 19/10/2016    , Tous publics                                           , Paramount                  , 4 274                    , 4 311       ,          ,                    0,                 3, 4                    , "[{""name"": ""Tom Cruise"", ""role_type"": ""Rôle principal"", ""character"": ""Jack Reacher""}]"

Ligne 27: 38 champs trouvés
Pulp Fiction                                             , https://www.jpbox-office.com/fichfilm.php?id=4252&view=2 , -                   , 2 864 640      , Quentin Tarantino           ,           , Etats-Unis      , Drame             , 26/10/1994    , Moins de 12 ans                                        , Bac Films                  , 951                      , 954         ,          ,                    1,                11, 1                    , "[{""name"": ""Bruce Willis"", ""role_type"": ""Rôle principal"", ""character"": ""Butch Coolidge""}, {""name"": ""John Travolta"", ""role_type"": ""Rôle principal"", ""character"": ""Vincent Vega""}, {""name"": ""Samuel L. Jackson"", ""role_type"": ""Rôle principal"", ""character"": """"}, {""name"": ""Uma Thurman"", ""role_type"": ""Rôle principal"", ""character"": ""Mia Wallace""}, {""name"": ""Harvey Keitel"", ""role_type"": ""Second rôle"", ""character"": """"}, {""name"": ""Christopher Walken"", ""role_type"": ""Apparition"", ""character"": """"}, {""name"": ""Steve Buscemi"", ""role_type"": """", ""character"": """"}]"

Ligne 28: 29 champs trouvés

In [18]:
df = pd.read_csv('normalized_18.csv', quotechar='"', skipinitialspace=True)

In [19]:
print(df.head())

  Titre                                                      \
0  Scream 4                                      ...
1  Resident Evil                                 ...
2  Mariages!                                     ...
3  Gainsbourg - (vie héroïque)                   ...
4  L'Homme qui murmurait à l'oreille des chevaux ...

  URL                                                        \
0  https://www.jpbox-office.com/fichfilm.php?id=1...
1  https://www.jpbox-office.com/fichfilm.php?id=1...
2  https://www.jpbox-office.com/fichfilm.php?id=1...
3  https://www.jpbox-office.com/fichfilm.php?id=1...
4  https://www.jpbox-office.com/fichfilm.php?id=3...

   Entrées 1ère semaine  Entrées totales  Réalisateur                   \
0  -                     1 070 890        Wes Craven
1  -                     1 105 943        Paul W.S. Anderson
2  -                     2 008 899                                 NaN
3  -                     1 199 451                                 NaN
4  -                     2 997 201        Robert Redford

   Producteur  Pays              Genre               Date de sortie  \
0         NaN  Etats-Unis        Horreur             13/04/2011
1         NaN  Etats-Unis        Aventure - Action   03/04/2002
2         NaN  France            Comédie             21/04/2004
3         NaN  France            Comédie dramatique  20/01/2010
4         NaN  Etats-Unis        Romance             02/09/1998

  Classification                                           \
0  Moins de 12 ans                               ...
1  Moins de 12 ans                               ...
2  Distribué par Pan-Européenne                  ...
3  Tous publics                                  ...
4  Tous publics                                  ...

   Distributeur                 Rang toutes exploitations  Rang général  \
0  SND                          3 754                      3 782
1  Metropolitan                 3 641                      3 670
2  Pan-Européenne               1 743                      1 757
3  Universal                    3 331                      3 359
4  GBVI                         869                        871

  Rang 2008  Nb 1ère places hebdo  Nb semaines Top20  Meilleure place hebdo  \
0       NaN                     0                  5  2
1       NaN                     0                  5  2
2       NaN                     1                  7  1
3       NaN                     0                  5  3
4       NaN                     2                  9  1

                                             Acteurs
0  [{"name": "Courteney Cox", "role_type": "Secon...
1  [{"name": "Milla Jovovich", "role_type": "Rôle...
2  [{"name": "Jean Dujardin", "role_type": "Rôle ...
3  [{"name": "Yolande Moreau", "role_type": "Seco...
4  [{"name": "Robert Redford", "role_type": "Rôle...

In [22]:
import pandas as pd

# Charger le fichier CSV
df = pd.read_csv('normalized_18.csv', quotechar='"', skipinitialspace=True)

# Afficher les 20 premières lignes
display(df.head(20))

,Titre,URL,Entrées 1ère semaine,Entrées totales,Réalisateur,Producteur,Pays,Genre,Date de sortie,Classification,Distributeur,Rang toutes exploitations,Rang général,Rang 2008,Nb 1ère places hebdo,Nb semaines Top20,Meilleure place hebdo,Acteurs
0,Scream 4 ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 070 890,Wes Craven,NaN,Etats-Unis,Horreur,13/04/2011,Moins de 12 ans ...,SND,3 754,3 782,NaN,0,5,2,"[{""name"": ""Courteney Cox"", ""role_type"": ""Secon..."
1,Resident Evil ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 105 943,Paul W.S. Anderson,NaN,Etats-Unis,Aventure - Action,03/04/2002,Moins de 12 ans ...,Metropolitan,3 641,3 670,NaN,0,5,2,"[{""name"": ""Milla Jovovich"", ""role_type"": ""Rôle..."
2,Mariages! ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,2 008 899,NaN,NaN,France,Comédie,21/04/2004,Distribué par Pan-Européenne ...,Pan-Européenne,1 743,1 757,NaN,1,7,1,"[{""name"": ""Jean Dujardin"", ""role_type"": ""Rôle ..."
3,Gainsbourg - (vie héroïque) ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 199 451,NaN,NaN,France,Comédie dramatique,20/01/2010,Tous publics ...,Universal,3 331,3 359,NaN,0,5,3,"[{""name"": ""Yolande Moreau"", ""role_type"": ""Seco..."
4,L'Homme qui murmurait à l'oreille des chevaux ...,https://www.jpbox-office.com/fichfilm.php?id=3...,-,2 997 201,Robert Redford,NaN,Etats-Unis,Romance,02/09/1998,Tous publics ...,GBVI,869,871,NaN,2,9,1,"[{""name"": ""Robert Redford"", ""role_type"": ""Rôle..."
5,La Fin des temps ...,https://www.jpbox-office.com/fichfilm.php?id=2...,-,1 298 541,Peter Hyams,NaN,Etats-Unis,Aventure - Action,15/12/1999,Moins de 12 ans ...,Metropolitan,3 038,3 063,NaN,0,6,2,"[{""name"": ""Arnold Schwarzenegger"", ""role_type""..."
6,De Gaulle ...,https://www.jpbox-office.com/fichfilm.php?id=2...,60 908,859 981,NaN,NaN,France,Drame,04/03/2020,Distribué par SND ...,SND,4 522,4 559,NaN,0,7,2,"[{""name"": ""Isabelle Carré"", ""role_type"": ""Rôle..."
7,Matrix Resurrections ...,https://www.jpbox-office.com/fichfilm.php?id=1...,50 587,972 644,Wachowski (brothers),NaN,Etats-Unis,Science Fiction,22/12/2021,Tous publics ...,Warner Bros.,4 112,4 148,NaN,0,5,3,"[{""name"": ""Carrie-Anne Moss"", ""role_type"": ""Rô..."
8,Casse-tête chinois ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 536 489,Cédric Klapisch,NaN,France,Comédie,04/12/2013,Tous publics ...,Studiocanal,2 502,2 523,NaN,0,6,3,"[{""name"": ""Cécile De France"", ""role_type"": ""Rô..."
9,Forrest Gump ...,https://www.jpbox-office.com/fichfilm.php?id=4...,-,3 963 919,Robert Zemeckis,NaN,Etats-Unis,Comédie,05/10/1994,Tous publics ...,UIP,471,465,NaN,1,13,1,"[{""name"": ""Tom Hanks"", ""role_type"": ""Rôle prin..."
10,La Vengeance d'une blonde ...,https://www.jpbox-office.com/fichfilm.php?id=4...,-,2 039 370,NaN,NaN,France,Comédie,26/01/1994,Distribué par AMLF ...,AMLF,1 711,1 725,NaN,1,6,1,"[{""name"": ""Christian Clavier"", ""role_type"": ""R..."
11,La Nuit au musée : Le Secret des Pharaons ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 576 649,Shawn Levy,NaN,Etats-Unis,Film familial,04/02/2015,Tous publics ...,20th Century Fox,2 430,2 451,NaN,0,5,2,"[{""name"": ""Ben Stiller"", ""role_type"": ""Rôle pr..."
12,Boudu ...,https://www.jpbox-office.com/fichfilm.php?id=7...,-,1 199 369,Gérard Jugnot,NaN,France,Comédie,09/03/2005,Distribué par Pathé ...,Pathé,3 332,3 360,NaN,1,5,1,"[{""name"": ""Gérard Depardieu"", ""role_type"": ""Rô..."
13,J'accuse ...,https://www.jpbox-office.com/fichfilm.php?id=1...,10 268,1 567 306,Roman Polanski,NaN,France,Drame,13/11/2019,Tous publics ...,Gaumont,2 445,2 466,NaN,1,6,1,"[{""name"": ""Jean Dujardin"", ""role_type"": ""Rôle ..."
14,Tigre et dragon ...,https://www.jpbox-office.com/fichfilm.php?id=2...,-,1 806 197,Ang Lee,NaN,Chine,Aventure - Action,04/10/2000,Tous publics ...,Warner Bros.,2 041,2 059,NaN,0,6,2,"[{""name"": ""Yun-Fat Chow"", ""role_type"": ""Rôle p..."
15,Les Femmes du 6e étage ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,2 213 187,NaN,NaN,France,Comédie,16/02/2011,Tous publics ...,SND,1 508,1 520,NaN,0,9,3,"[{""name"": ""Sandrine Kiberlain"", ""role_type"": ""..."
16,Speed 2 ...,https://www.jpbox-office.com/fichfilm.php?id=3...,-,1 134 913,Jan De Bont,NaN,Etats-Unis,Aventure - Action,23/07/1997,Tous publics ...,UFD,3 549,3 579,NaN,2,5,1,"[{""name"": ""Sandra Bullock"", ""role_type"": ""Rôle..."
17,Sully ...,https://www.jpbox-office.com/fichfilm.php?id=1...,14 345,1 178 535,Clint Eastwood,NaN,Etats-Unis,Drame,30/11/2016,Tous publics ...,Warner Bros.,3 397,3 425,NaN,0,5,3,"[{""name"": ""Tom Hanks"", ""role_type"": ""Rôle prin..."
18,Ali ...,https://www.jpbox-office.com/fichfilm.php?id=2...,-,1 035 360,Michael Mann,NaN,Etats-Unis,Drame,27/02/2002,Distribué par Bac Films ...,Bac Films,3 876,3 906,NaN,0,5,2,"[{""name"": ""Will Smith"", ""role_type"": ""Rôle pri..."
19,"Tanguy, le retour ...",https://www.jpbox-office.com/fichfilm.php?id=1...,30 252,1 027 447,Etienne Chatiliez,NaN,France,Comédie,10/04/2019,Tous publics ...,SND,3 902,3 932,NaN,1,6,1,"[{""name"": ""Sabine Azéma"", ""role_type"": ""Rôle p..."

In [24]:
df.to_csv('normalized_18.csv', index=False, quoting=1)  # 1 correspond à csv.QUOTE_ALL
df = pd.read_csv('normalized_18.csv', skipinitialspace=True)

In [25]:
df.head(20)

,Titre,URL,Entrées 1ère semaine,Entrées totales,Réalisateur,Producteur,Pays,Genre,Date de sortie,Classification,Distributeur,Rang toutes exploitations,Rang général,Rang 2008,Nb 1ère places hebdo,Nb semaines Top20,Meilleure place hebdo,Acteurs
0,Scream 4 ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 070 890,Wes Craven,NaN,Etats-Unis,Horreur,13/04/2011,Moins de 12 ans ...,SND,3 754,3 782,NaN,0,5,2,"[{""name"": ""Courteney Cox"", ""role_type"": ""Secon..."
1,Resident Evil ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 105 943,Paul W.S. Anderson,NaN,Etats-Unis,Aventure - Action,03/04/2002,Moins de 12 ans ...,Metropolitan,3 641,3 670,NaN,0,5,2,"[{""name"": ""Milla Jovovich"", ""role_type"": ""Rôle..."
2,Mariages! ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,2 008 899,NaN,NaN,France,Comédie,21/04/2004,Distribué par Pan-Européenne ...,Pan-Européenne,1 743,1 757,NaN,1,7,1,"[{""name"": ""Jean Dujardin"", ""role_type"": ""Rôle ..."
3,Gainsbourg - (vie héroïque) ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 199 451,NaN,NaN,France,Comédie dramatique,20/01/2010,Tous publics ...,Universal,3 331,3 359,NaN,0,5,3,"[{""name"": ""Yolande Moreau"", ""role_type"": ""Seco..."
4,L'Homme qui murmurait à l'oreille des chevaux ...,https://www.jpbox-office.com/fichfilm.php?id=3...,-,2 997 201,Robert Redford,NaN,Etats-Unis,Romance,02/09/1998,Tous publics ...,GBVI,869,871,NaN,2,9,1,"[{""name"": ""Robert Redford"", ""role_type"": ""Rôle..."
5,La Fin des temps ...,https://www.jpbox-office.com/fichfilm.php?id=2...,-,1 298 541,Peter Hyams,NaN,Etats-Unis,Aventure - Action,15/12/1999,Moins de 12 ans ...,Metropolitan,3 038,3 063,NaN,0,6,2,"[{""name"": ""Arnold Schwarzenegger"", ""role_type""..."
6,De Gaulle ...,https://www.jpbox-office.com/fichfilm.php?id=2...,60 908,859 981,NaN,NaN,France,Drame,04/03/2020,Distribué par SND ...,SND,4 522,4 559,NaN,0,7,2,"[{""name"": ""Isabelle Carré"", ""role_type"": ""Rôle..."
7,Matrix Resurrections ...,https://www.jpbox-office.com/fichfilm.php?id=1...,50 587,972 644,Wachowski (brothers),NaN,Etats-Unis,Science Fiction,22/12/2021,Tous publics ...,Warner Bros.,4 112,4 148,NaN,0,5,3,"[{""name"": ""Carrie-Anne Moss"", ""role_type"": ""Rô..."
8,Casse-tête chinois ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 536 489,Cédric Klapisch,NaN,France,Comédie,04/12/2013,Tous publics ...,Studiocanal,2 502,2 523,NaN,0,6,3,"[{""name"": ""Cécile De France"", ""role_type"": ""Rô..."
9,Forrest Gump ...,https://www.jpbox-office.com/fichfilm.php?id=4...,-,3 963 919,Robert Zemeckis,NaN,Etats-Unis,Comédie,05/10/1994,Tous publics ...,UIP,471,465,NaN,1,13,1,"[{""name"": ""Tom Hanks"", ""role_type"": ""Rôle prin..."
10,La Vengeance d'une blonde ...,https://www.jpbox-office.com/fichfilm.php?id=4...,-,2 039 370,NaN,NaN,France,Comédie,26/01/1994,Distribué par AMLF ...,AMLF,1 711,1 725,NaN,1,6,1,"[{""name"": ""Christian Clavier"", ""role_type"": ""R..."
11,La Nuit au musée : Le Secret des Pharaons ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 576 649,Shawn Levy,NaN,Etats-Unis,Film familial,04/02/2015,Tous publics ...,20th Century Fox,2 430,2 451,NaN,0,5,2,"[{""name"": ""Ben Stiller"", ""role_type"": ""Rôle pr..."
12,Boudu ...,https://www.jpbox-office.com/fichfilm.php?id=7...,-,1 199 369,Gérard Jugnot,NaN,France,Comédie,09/03/2005,Distribué par Pathé ...,Pathé,3 332,3 360,NaN,1,5,1,"[{""name"": ""Gérard Depardieu"", ""role_type"": ""Rô..."
13,J'accuse ...,https://www.jpbox-office.com/fichfilm.php?id=1...,10 268,1 567 306,Roman Polanski,NaN,France,Drame,13/11/2019,Tous publics ...,Gaumont,2 445,2 466,NaN,1,6,1,"[{""name"": ""Jean Dujardin"", ""role_type"": ""Rôle ..."
14,Tigre et dragon ...,https://www.jpbox-office.com/fichfilm.php?id=2...,-,1 806 197,Ang Lee,NaN,Chine,Aventure - Action,04/10/2000,Tous publics ...,Warner Bros.,2 041,2 059,NaN,0,6,2,"[{""name"": ""Yun-Fat Chow"", ""role_type"": ""Rôle p..."
15,Les Femmes du 6e étage ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,2 213 187,NaN,NaN,France,Comédie,16/02/2011,Tous publics ...,SND,1 508,1 520,NaN,0,9,3,"[{""name"": ""Sandrine Kiberlain"", ""role_type"": ""..."
16,Speed 2 ...,https://www.jpbox-office.com/fichfilm.php?id=3...,-,1 134 913,Jan De Bont,NaN,Etats-Unis,Aventure - Action,23/07/1997,Tous publics ...,UFD,3 549,3 579,NaN,2,5,1,"[{""name"": ""Sandra Bullock"", ""role_type"": ""Rôle..."
17,Sully ...,https://www.jpbox-office.com/fichfilm.php?id=1...,14 345,1 178 535,Clint Eastwood,NaN,Etats-Unis,Drame,30/11/2016,Tous publics ...,Warner Bros.,3 397,3 425,NaN,0,5,3,"[{""name"": ""Tom Hanks"", ""role_type"": ""Rôle prin..."
18,Ali ...,https://www.jpbox-office.com/fichfilm.php?id=2...,-,1 035 360,Michael Mann,NaN,Etats-Unis,Drame,27/02/2002,Distribué par Bac Films ...,Bac Films,3 876,3 906,NaN,0,5,2,"[{""name"": ""Will Smith"", ""role_type"": ""Rôle pri..."
19,"Tanguy, le retour ...",https://www.jpbox-office.com/fichfilm.php?id=1...,30 252,1 027 447,Etienne Chatiliez,NaN,France,Comédie,10/04/2019,Tous publics ...,SND,3 902,3 932,NaN,1,6,1,"[{""name"": ""Sabine Azéma"", ""role_type"": ""Rôle p..."

In [26]:
df.to_csv('invalid_17.csv', index=False, quoting=1)  # 1 correspond à csv.QUOTE_ALL
df = pd.read_csv('invalid_17.csv', skipinitialspace=True)

In [27]:
df.head(20)

,Titre,URL,Entrées 1ère semaine,Entrées totales,Réalisateur,Producteur,Pays,Genre,Date de sortie,Classification,Distributeur,Rang toutes exploitations,Rang général,Rang 2008,Nb 1ère places hebdo,Nb semaines Top20,Meilleure place hebdo,Acteurs
0,Scream 4 ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 070 890,Wes Craven,NaN,Etats-Unis,Horreur,13/04/2011,Moins de 12 ans ...,SND,3 754,3 782,NaN,0,5,2,"[{""name"": ""Courteney Cox"", ""role_type"": ""Secon..."
1,Resident Evil ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 105 943,Paul W.S. Anderson,NaN,Etats-Unis,Aventure - Action,03/04/2002,Moins de 12 ans ...,Metropolitan,3 641,3 670,NaN,0,5,2,"[{""name"": ""Milla Jovovich"", ""role_type"": ""Rôle..."
2,Mariages! ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,2 008 899,NaN,NaN,France,Comédie,21/04/2004,Distribué par Pan-Européenne ...,Pan-Européenne,1 743,1 757,NaN,1,7,1,"[{""name"": ""Jean Dujardin"", ""role_type"": ""Rôle ..."
3,Gainsbourg - (vie héroïque) ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 199 451,NaN,NaN,France,Comédie dramatique,20/01/2010,Tous publics ...,Universal,3 331,3 359,NaN,0,5,3,"[{""name"": ""Yolande Moreau"", ""role_type"": ""Seco..."
4,L'Homme qui murmurait à l'oreille des chevaux ...,https://www.jpbox-office.com/fichfilm.php?id=3...,-,2 997 201,Robert Redford,NaN,Etats-Unis,Romance,02/09/1998,Tous publics ...,GBVI,869,871,NaN,2,9,1,"[{""name"": ""Robert Redford"", ""role_type"": ""Rôle..."
5,La Fin des temps ...,https://www.jpbox-office.com/fichfilm.php?id=2...,-,1 298 541,Peter Hyams,NaN,Etats-Unis,Aventure - Action,15/12/1999,Moins de 12 ans ...,Metropolitan,3 038,3 063,NaN,0,6,2,"[{""name"": ""Arnold Schwarzenegger"", ""role_type""..."
6,De Gaulle ...,https://www.jpbox-office.com/fichfilm.php?id=2...,60 908,859 981,NaN,NaN,France,Drame,04/03/2020,Distribué par SND ...,SND,4 522,4 559,NaN,0,7,2,"[{""name"": ""Isabelle Carré"", ""role_type"": ""Rôle..."
7,Matrix Resurrections ...,https://www.jpbox-office.com/fichfilm.php?id=1...,50 587,972 644,Wachowski (brothers),NaN,Etats-Unis,Science Fiction,22/12/2021,Tous publics ...,Warner Bros.,4 112,4 148,NaN,0,5,3,"[{""name"": ""Carrie-Anne Moss"", ""role_type"": ""Rô..."
8,Casse-tête chinois ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 536 489,Cédric Klapisch,NaN,France,Comédie,04/12/2013,Tous publics ...,Studiocanal,2 502,2 523,NaN,0,6,3,"[{""name"": ""Cécile De France"", ""role_type"": ""Rô..."
9,Forrest Gump ...,https://www.jpbox-office.com/fichfilm.php?id=4...,-,3 963 919,Robert Zemeckis,NaN,Etats-Unis,Comédie,05/10/1994,Tous publics ...,UIP,471,465,NaN,1,13,1,"[{""name"": ""Tom Hanks"", ""role_type"": ""Rôle prin..."
10,La Vengeance d'une blonde ...,https://www.jpbox-office.com/fichfilm.php?id=4...,-,2 039 370,NaN,NaN,France,Comédie,26/01/1994,Distribué par AMLF ...,AMLF,1 711,1 725,NaN,1,6,1,"[{""name"": ""Christian Clavier"", ""role_type"": ""R..."
11,La Nuit au musée : Le Secret des Pharaons ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 576 649,Shawn Levy,NaN,Etats-Unis,Film familial,04/02/2015,Tous publics ...,20th Century Fox,2 430,2 451,NaN,0,5,2,"[{""name"": ""Ben Stiller"", ""role_type"": ""Rôle pr..."
12,Boudu ...,https://www.jpbox-office.com/fichfilm.php?id=7...,-,1 199 369,Gérard Jugnot,NaN,France,Comédie,09/03/2005,Distribué par Pathé ...,Pathé,3 332,3 360,NaN,1,5,1,"[{""name"": ""Gérard Depardieu"", ""role_type"": ""Rô..."
13,J'accuse ...,https://www.jpbox-office.com/fichfilm.php?id=1...,10 268,1 567 306,Roman Polanski,NaN,France,Drame,13/11/2019,Tous publics ...,Gaumont,2 445,2 466,NaN,1,6,1,"[{""name"": ""Jean Dujardin"", ""role_type"": ""Rôle ..."
14,Tigre et dragon ...,https://www.jpbox-office.com/fichfilm.php?id=2...,-,1 806 197,Ang Lee,NaN,Chine,Aventure - Action,04/10/2000,Tous publics ...,Warner Bros.,2 041,2 059,NaN,0,6,2,"[{""name"": ""Yun-Fat Chow"", ""role_type"": ""Rôle p..."
15,Les Femmes du 6e étage ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,2 213 187,NaN,NaN,France,Comédie,16/02/2011,Tous publics ...,SND,1 508,1 520,NaN,0,9,3,"[{""name"": ""Sandrine Kiberlain"", ""role_type"": ""..."
16,Speed 2 ...,https://www.jpbox-office.com/fichfilm.php?id=3...,-,1 134 913,Jan De Bont,NaN,Etats-Unis,Aventure - Action,23/07/1997,Tous publics ...,UFD,3 549,3 579,NaN,2,5,1,"[{""name"": ""Sandra Bullock"", ""role_type"": ""Rôle..."
17,Sully ...,https://www.jpbox-office.com/fichfilm.php?id=1...,14 345,1 178 535,Clint Eastwood,NaN,Etats-Unis,Drame,30/11/2016,Tous publics ...,Warner Bros.,3 397,3 425,NaN,0,5,3,"[{""name"": ""Tom Hanks"", ""role_type"": ""Rôle prin..."
18,Ali ...,https://www.jpbox-office.com/fichfilm.php?id=2...,-,1 035 360,Michael Mann,NaN,Etats-Unis,Drame,27/02/2002,Distribué par Bac Films ...,Bac Films,3 876,3 906,NaN,0,5,2,"[{""name"": ""Will Smith"", ""role_type"": ""Rôle pri..."
19,"Tanguy, le retour ...",https://www.jpbox-office.com/fichfilm.php?id=1...,30 252,1 027 447,Etienne Chatiliez,NaN,France,Comédie,10/04/2019,Tous publics ...,SND,3 902,3 932,NaN,1,6,1,"[{""name"": ""Sabine Azéma"", ""role_type"": ""Rôle p..."

In [28]:
df.to_csv('listfilmjpbox.csv', index=False, quoting=1)  # 1 correspond à csv.QUOTE_ALL
df = pd.read_csv('listfilmjpbox.csv', skipinitialspace=True)

In [29]:
df.head(20)

,Titre,URL,Entrées 1ère semaine,Entrées totales,Réalisateur,Producteur,Pays,Genre,Date de sortie,Classification,Distributeur,Rang toutes exploitations,Rang général,Rang 2008,Nb 1ère places hebdo,Nb semaines Top20,Meilleure place hebdo,Acteurs
0,Scream 4 ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 070 890,Wes Craven,NaN,Etats-Unis,Horreur,13/04/2011,Moins de 12 ans ...,SND,3 754,3 782,NaN,0,5,2,"[{""name"": ""Courteney Cox"", ""role_type"": ""Secon..."
1,Resident Evil ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 105 943,Paul W.S. Anderson,NaN,Etats-Unis,Aventure - Action,03/04/2002,Moins de 12 ans ...,Metropolitan,3 641,3 670,NaN,0,5,2,"[{""name"": ""Milla Jovovich"", ""role_type"": ""Rôle..."
2,Mariages! ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,2 008 899,NaN,NaN,France,Comédie,21/04/2004,Distribué par Pan-Européenne ...,Pan-Européenne,1 743,1 757,NaN,1,7,1,"[{""name"": ""Jean Dujardin"", ""role_type"": ""Rôle ..."
3,Gainsbourg - (vie héroïque) ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 199 451,NaN,NaN,France,Comédie dramatique,20/01/2010,Tous publics ...,Universal,3 331,3 359,NaN,0,5,3,"[{""name"": ""Yolande Moreau"", ""role_type"": ""Seco..."
4,L'Homme qui murmurait à l'oreille des chevaux ...,https://www.jpbox-office.com/fichfilm.php?id=3...,-,2 997 201,Robert Redford,NaN,Etats-Unis,Romance,02/09/1998,Tous publics ...,GBVI,869,871,NaN,2,9,1,"[{""name"": ""Robert Redford"", ""role_type"": ""Rôle..."
5,La Fin des temps ...,https://www.jpbox-office.com/fichfilm.php?id=2...,-,1 298 541,Peter Hyams,NaN,Etats-Unis,Aventure - Action,15/12/1999,Moins de 12 ans ...,Metropolitan,3 038,3 063,NaN,0,6,2,"[{""name"": ""Arnold Schwarzenegger"", ""role_type""..."
6,De Gaulle ...,https://www.jpbox-office.com/fichfilm.php?id=2...,60 908,859 981,NaN,NaN,France,Drame,04/03/2020,Distribué par SND ...,SND,4 522,4 559,NaN,0,7,2,"[{""name"": ""Isabelle Carré"", ""role_type"": ""Rôle..."
7,Matrix Resurrections ...,https://www.jpbox-office.com/fichfilm.php?id=1...,50 587,972 644,Wachowski (brothers),NaN,Etats-Unis,Science Fiction,22/12/2021,Tous publics ...,Warner Bros.,4 112,4 148,NaN,0,5,3,"[{""name"": ""Carrie-Anne Moss"", ""role_type"": ""Rô..."
8,Casse-tête chinois ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 536 489,Cédric Klapisch,NaN,France,Comédie,04/12/2013,Tous publics ...,Studiocanal,2 502,2 523,NaN,0,6,3,"[{""name"": ""Cécile De France"", ""role_type"": ""Rô..."
9,Forrest Gump ...,https://www.jpbox-office.com/fichfilm.php?id=4...,-,3 963 919,Robert Zemeckis,NaN,Etats-Unis,Comédie,05/10/1994,Tous publics ...,UIP,471,465,NaN,1,13,1,"[{""name"": ""Tom Hanks"", ""role_type"": ""Rôle prin..."
10,La Vengeance d'une blonde ...,https://www.jpbox-office.com/fichfilm.php?id=4...,-,2 039 370,NaN,NaN,France,Comédie,26/01/1994,Distribué par AMLF ...,AMLF,1 711,1 725,NaN,1,6,1,"[{""name"": ""Christian Clavier"", ""role_type"": ""R..."
11,La Nuit au musée : Le Secret des Pharaons ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 576 649,Shawn Levy,NaN,Etats-Unis,Film familial,04/02/2015,Tous publics ...,20th Century Fox,2 430,2 451,NaN,0,5,2,"[{""name"": ""Ben Stiller"", ""role_type"": ""Rôle pr..."
12,Boudu ...,https://www.jpbox-office.com/fichfilm.php?id=7...,-,1 199 369,Gérard Jugnot,NaN,France,Comédie,09/03/2005,Distribué par Pathé ...,Pathé,3 332,3 360,NaN,1,5,1,"[{""name"": ""Gérard Depardieu"", ""role_type"": ""Rô..."
13,J'accuse ...,https://www.jpbox-office.com/fichfilm.php?id=1...,10 268,1 567 306,Roman Polanski,NaN,France,Drame,13/11/2019,Tous publics ...,Gaumont,2 445,2 466,NaN,1,6,1,"[{""name"": ""Jean Dujardin"", ""role_type"": ""Rôle ..."
14,Tigre et dragon ...,https://www.jpbox-office.com/fichfilm.php?id=2...,-,1 806 197,Ang Lee,NaN,Chine,Aventure - Action,04/10/2000,Tous publics ...,Warner Bros.,2 041,2 059,NaN,0,6,2,"[{""name"": ""Yun-Fat Chow"", ""role_type"": ""Rôle p..."
15,Les Femmes du 6e étage ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,2 213 187,NaN,NaN,France,Comédie,16/02/2011,Tous publics ...,SND,1 508,1 520,NaN,0,9,3,"[{""name"": ""Sandrine Kiberlain"", ""role_type"": ""..."
16,Speed 2 ...,https://www.jpbox-office.com/fichfilm.php?id=3...,-,1 134 913,Jan De Bont,NaN,Etats-Unis,Aventure - Action,23/07/1997,Tous publics ...,UFD,3 549,3 579,NaN,2,5,1,"[{""name"": ""Sandra Bullock"", ""role_type"": ""Rôle..."
17,Sully ...,https://www.jpbox-office.com/fichfilm.php?id=1...,14 345,1 178 535,Clint Eastwood,NaN,Etats-Unis,Drame,30/11/2016,Tous publics ...,Warner Bros.,3 397,3 425,NaN,0,5,3,"[{""name"": ""Tom Hanks"", ""role_type"": ""Rôle prin..."
18,Ali ...,https://www.jpbox-office.com/fichfilm.php?id=2...,-,1 035 360,Michael Mann,NaN,Etats-Unis,Drame,27/02/2002,Distribué par Bac Films ...,Bac Films,3 876,3 906,NaN,0,5,2,"[{""name"": ""Will Smith"", ""role_type"": ""Rôle pri..."
19,"Tanguy, le retour ...",https://www.jpbox-office.com/fichfilm.php?id=1...,30 252,1 027 447,Etienne Chatiliez,NaN,France,Comédie,10/04/2019,Tous publics ...,SND,3 902,3 932,NaN,1,6,1,"[{""name"": ""Sabine Azéma"", ""role_type"": ""Rôle p..."

In [32]:
df.to_csv('demarage.csv', index=False, quoting=1)  # 1 correspond à csv.QUOTE_ALL
df = pd.read_csv('demarage.csv', skipinitialspace=True)
df.head(20)

,Titre,URL,Entrées 1ère semaine,Entrées totales,Réalisateur,Producteur,Pays,Genre,Date de sortie,Classification,Distributeur,Rang toutes exploitations,Rang général,Rang 2008,Nb 1ère places hebdo,Nb semaines Top20,Meilleure place hebdo,Acteurs
0,Scream 4 ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 070 890,Wes Craven,NaN,Etats-Unis,Horreur,13/04/2011,Moins de 12 ans ...,SND,3 754,3 782,NaN,0,5,2,"[{""name"": ""Courteney Cox"", ""role_type"": ""Secon..."
1,Resident Evil ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 105 943,Paul W.S. Anderson,NaN,Etats-Unis,Aventure - Action,03/04/2002,Moins de 12 ans ...,Metropolitan,3 641,3 670,NaN,0,5,2,"[{""name"": ""Milla Jovovich"", ""role_type"": ""Rôle..."
2,Mariages! ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,2 008 899,NaN,NaN,France,Comédie,21/04/2004,Distribué par Pan-Européenne ...,Pan-Européenne,1 743,1 757,NaN,1,7,1,"[{""name"": ""Jean Dujardin"", ""role_type"": ""Rôle ..."
3,Gainsbourg - (vie héroïque) ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 199 451,NaN,NaN,France,Comédie dramatique,20/01/2010,Tous publics ...,Universal,3 331,3 359,NaN,0,5,3,"[{""name"": ""Yolande Moreau"", ""role_type"": ""Seco..."
4,L'Homme qui murmurait à l'oreille des chevaux ...,https://www.jpbox-office.com/fichfilm.php?id=3...,-,2 997 201,Robert Redford,NaN,Etats-Unis,Romance,02/09/1998,Tous publics ...,GBVI,869,871,NaN,2,9,1,"[{""name"": ""Robert Redford"", ""role_type"": ""Rôle..."
5,La Fin des temps ...,https://www.jpbox-office.com/fichfilm.php?id=2...,-,1 298 541,Peter Hyams,NaN,Etats-Unis,Aventure - Action,15/12/1999,Moins de 12 ans ...,Metropolitan,3 038,3 063,NaN,0,6,2,"[{""name"": ""Arnold Schwarzenegger"", ""role_type""..."
6,De Gaulle ...,https://www.jpbox-office.com/fichfilm.php?id=2...,60 908,859 981,NaN,NaN,France,Drame,04/03/2020,Distribué par SND ...,SND,4 522,4 559,NaN,0,7,2,"[{""name"": ""Isabelle Carré"", ""role_type"": ""Rôle..."
7,Matrix Resurrections ...,https://www.jpbox-office.com/fichfilm.php?id=1...,50 587,972 644,Wachowski (brothers),NaN,Etats-Unis,Science Fiction,22/12/2021,Tous publics ...,Warner Bros.,4 112,4 148,NaN,0,5,3,"[{""name"": ""Carrie-Anne Moss"", ""role_type"": ""Rô..."
8,Casse-tête chinois ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 536 489,Cédric Klapisch,NaN,France,Comédie,04/12/2013,Tous publics ...,Studiocanal,2 502,2 523,NaN,0,6,3,"[{""name"": ""Cécile De France"", ""role_type"": ""Rô..."
9,Forrest Gump ...,https://www.jpbox-office.com/fichfilm.php?id=4...,-,3 963 919,Robert Zemeckis,NaN,Etats-Unis,Comédie,05/10/1994,Tous publics ...,UIP,471,465,NaN,1,13,1,"[{""name"": ""Tom Hanks"", ""role_type"": ""Rôle prin..."
10,La Vengeance d'une blonde ...,https://www.jpbox-office.com/fichfilm.php?id=4...,-,2 039 370,NaN,NaN,France,Comédie,26/01/1994,Distribué par AMLF ...,AMLF,1 711,1 725,NaN,1,6,1,"[{""name"": ""Christian Clavier"", ""role_type"": ""R..."
11,La Nuit au musée : Le Secret des Pharaons ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 576 649,Shawn Levy,NaN,Etats-Unis,Film familial,04/02/2015,Tous publics ...,20th Century Fox,2 430,2 451,NaN,0,5,2,"[{""name"": ""Ben Stiller"", ""role_type"": ""Rôle pr..."
12,Boudu ...,https://www.jpbox-office.com/fichfilm.php?id=7...,-,1 199 369,Gérard Jugnot,NaN,France,Comédie,09/03/2005,Distribué par Pathé ...,Pathé,3 332,3 360,NaN,1,5,1,"[{""name"": ""Gérard Depardieu"", ""role_type"": ""Rô..."
13,J'accuse ...,https://www.jpbox-office.com/fichfilm.php?id=1...,10 268,1 567 306,Roman Polanski,NaN,France,Drame,13/11/2019,Tous publics ...,Gaumont,2 445,2 466,NaN,1,6,1,"[{""name"": ""Jean Dujardin"", ""role_type"": ""Rôle ..."
14,Tigre et dragon ...,https://www.jpbox-office.com/fichfilm.php?id=2...,-,1 806 197,Ang Lee,NaN,Chine,Aventure - Action,04/10/2000,Tous publics ...,Warner Bros.,2 041,2 059,NaN,0,6,2,"[{""name"": ""Yun-Fat Chow"", ""role_type"": ""Rôle p..."
15,Les Femmes du 6e étage ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,2 213 187,NaN,NaN,France,Comédie,16/02/2011,Tous publics ...,SND,1 508,1 520,NaN,0,9,3,"[{""name"": ""Sandrine Kiberlain"", ""role_type"": ""..."
16,Speed 2 ...,https://www.jpbox-office.com/fichfilm.php?id=3...,-,1 134 913,Jan De Bont,NaN,Etats-Unis,Aventure - Action,23/07/1997,Tous publics ...,UFD,3 549,3 579,NaN,2,5,1,"[{""name"": ""Sandra Bullock"", ""role_type"": ""Rôle..."
17,Sully ...,https://www.jpbox-office.com/fichfilm.php?id=1...,14 345,1 178 535,Clint Eastwood,NaN,Etats-Unis,Drame,30/11/2016,Tous publics ...,Warner Bros.,3 397,3 425,NaN,0,5,3,"[{""name"": ""Tom Hanks"", ""role_type"": ""Rôle prin..."
18,Ali ...,https://www.jpbox-office.com/fichfilm.php?id=2...,-,1 035 360,Michael Mann,NaN,Etats-Unis,Drame,27/02/2002,Distribué par Bac Films ...,Bac Films,3 876,3 906,NaN,0,5,2,"[{""name"": ""Will Smith"", ""role_type"": ""Rôle pri..."
19,"Tanguy, le retour ...",https://www.jpbox-office.com/fichfilm.php?id=1...,30 252,1 027 447,Etienne Chatiliez,NaN,France,Comédie,10/04/2019,Tous publics ...,SND,3 902,3 932,NaN,1,6,1,"[{""name"": ""Sabine Azéma"", ""role_type"": ""Rôle p..."

In [4]:
df_demarage = pd.read_csv('demarage.csv', skipinitialspace=True)
df_demarage.head(20)

                                           Titre Démarrage
0                                           1:54    21 207
1                       2 doigts sur la gâchette    67 951
2         2 garçons une fille trois possibilités    94 598
3                             2 Days In New York   144 635
4                                2 Days in Paris    56 415
5                                   Les 2 Alfred   118 883
6                                East Side Story         -
7                                     Gansta cop         -
8                            I Am Because We Are     4 358
9                     Gangsters, sexe et karaoké     3 990
10                                             M    13 015
11                                        R.I.F.   126 589
12                                             U    42 904
13  Wallace et Gromit: Le Mystère du lapin-garou   452 343
14       Y a-t-il enfin un pilote dans l'avion ?         -
15                                    You People       NaN
16                                         Zorro         -
17              Zorro et les Trois Mousquetaires         -
18                                 Zorba le grec         -
19                                Zora la rousse       NaN

In [36]:
df_film = pd.read_csv('listfilmjpbox.csv', skipinitialspace=True)
df_film.head(20)

,Titre,URL,Entrées 1ère semaine,Entrées totales,Réalisateur,Producteur,Pays,Genre,Date de sortie,Classification,Distributeur,Rang toutes exploitations,Rang général,Rang 2008,Nb 1ère places hebdo,Nb semaines Top20,Meilleure place hebdo,Acteurs
0,Scream 4 ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 070 890,Wes Craven,NaN,Etats-Unis,Horreur,13/04/2011,Moins de 12 ans ...,SND,3 754,3 782,NaN,0,5,2,"[{""name"": ""Courteney Cox"", ""role_type"": ""Secon..."
1,Resident Evil ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 105 943,Paul W.S. Anderson,NaN,Etats-Unis,Aventure - Action,03/04/2002,Moins de 12 ans ...,Metropolitan,3 641,3 670,NaN,0,5,2,"[{""name"": ""Milla Jovovich"", ""role_type"": ""Rôle..."
2,Mariages! ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,2 008 899,NaN,NaN,France,Comédie,21/04/2004,Distribué par Pan-Européenne ...,Pan-Européenne,1 743,1 757,NaN,1,7,1,"[{""name"": ""Jean Dujardin"", ""role_type"": ""Rôle ..."
3,Gainsbourg - (vie héroïque) ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 199 451,NaN,NaN,France,Comédie dramatique,20/01/2010,Tous publics ...,Universal,3 331,3 359,NaN,0,5,3,"[{""name"": ""Yolande Moreau"", ""role_type"": ""Seco..."
4,L'Homme qui murmurait à l'oreille des chevaux ...,https://www.jpbox-office.com/fichfilm.php?id=3...,-,2 997 201,Robert Redford,NaN,Etats-Unis,Romance,02/09/1998,Tous publics ...,GBVI,869,871,NaN,2,9,1,"[{""name"": ""Robert Redford"", ""role_type"": ""Rôle..."
5,La Fin des temps ...,https://www.jpbox-office.com/fichfilm.php?id=2...,-,1 298 541,Peter Hyams,NaN,Etats-Unis,Aventure - Action,15/12/1999,Moins de 12 ans ...,Metropolitan,3 038,3 063,NaN,0,6,2,"[{""name"": ""Arnold Schwarzenegger"", ""role_type""..."
6,De Gaulle ...,https://www.jpbox-office.com/fichfilm.php?id=2...,60 908,859 981,NaN,NaN,France,Drame,04/03/2020,Distribué par SND ...,SND,4 522,4 559,NaN,0,7,2,"[{""name"": ""Isabelle Carré"", ""role_type"": ""Rôle..."
7,Matrix Resurrections ...,https://www.jpbox-office.com/fichfilm.php?id=1...,50 587,972 644,Wachowski (brothers),NaN,Etats-Unis,Science Fiction,22/12/2021,Tous publics ...,Warner Bros.,4 112,4 148,NaN,0,5,3,"[{""name"": ""Carrie-Anne Moss"", ""role_type"": ""Rô..."
8,Casse-tête chinois ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 536 489,Cédric Klapisch,NaN,France,Comédie,04/12/2013,Tous publics ...,Studiocanal,2 502,2 523,NaN,0,6,3,"[{""name"": ""Cécile De France"", ""role_type"": ""Rô..."
9,Forrest Gump ...,https://www.jpbox-office.com/fichfilm.php?id=4...,-,3 963 919,Robert Zemeckis,NaN,Etats-Unis,Comédie,05/10/1994,Tous publics ...,UIP,471,465,NaN,1,13,1,"[{""name"": ""Tom Hanks"", ""role_type"": ""Rôle prin..."
10,La Vengeance d'une blonde ...,https://www.jpbox-office.com/fichfilm.php?id=4...,-,2 039 370,NaN,NaN,France,Comédie,26/01/1994,Distribué par AMLF ...,AMLF,1 711,1 725,NaN,1,6,1,"[{""name"": ""Christian Clavier"", ""role_type"": ""R..."
11,La Nuit au musée : Le Secret des Pharaons ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,1 576 649,Shawn Levy,NaN,Etats-Unis,Film familial,04/02/2015,Tous publics ...,20th Century Fox,2 430,2 451,NaN,0,5,2,"[{""name"": ""Ben Stiller"", ""role_type"": ""Rôle pr..."
12,Boudu ...,https://www.jpbox-office.com/fichfilm.php?id=7...,-,1 199 369,Gérard Jugnot,NaN,France,Comédie,09/03/2005,Distribué par Pathé ...,Pathé,3 332,3 360,NaN,1,5,1,"[{""name"": ""Gérard Depardieu"", ""role_type"": ""Rô..."
13,J'accuse ...,https://www.jpbox-office.com/fichfilm.php?id=1...,10 268,1 567 306,Roman Polanski,NaN,France,Drame,13/11/2019,Tous publics ...,Gaumont,2 445,2 466,NaN,1,6,1,"[{""name"": ""Jean Dujardin"", ""role_type"": ""Rôle ..."
14,Tigre et dragon ...,https://www.jpbox-office.com/fichfilm.php?id=2...,-,1 806 197,Ang Lee,NaN,Chine,Aventure - Action,04/10/2000,Tous publics ...,Warner Bros.,2 041,2 059,NaN,0,6,2,"[{""name"": ""Yun-Fat Chow"", ""role_type"": ""Rôle p..."
15,Les Femmes du 6e étage ...,https://www.jpbox-office.com/fichfilm.php?id=1...,-,2 213 187,NaN,NaN,France,Comédie,16/02/2011,Tous publics ...,SND,1 508,1 520,NaN,0,9,3,"[{""name"": ""Sandrine Kiberlain"", ""role_type"": ""..."
16,Speed 2 ...,https://www.jpbox-office.com/fichfilm.php?id=3...,-,1 134 913,Jan De Bont,NaN,Etats-Unis,Aventure - Action,23/07/1997,Tous publics ...,UFD,3 549,3 579,NaN,2,5,1,"[{""name"": ""Sandra Bullock"", ""role_type"": ""Rôle..."
17,Sully ...,https://www.jpbox-office.com/fichfilm.php?id=1...,14 345,1 178 535,Clint Eastwood,NaN,Etats-Unis,Drame,30/11/2016,Tous publics ...,Warner Bros.,3 397,3 425,NaN,0,5,3,"[{""name"": ""Tom Hanks"", ""role_type"": ""Rôle prin..."
18,Ali ...,https://www.jpbox-office.com/fichfilm.php?id=2...,-,1 035 360,Michael Mann,NaN,Etats-Unis,Drame,27/02/2002,Distribué par Bac Films ...,Bac Films,3 876,3 906,NaN,0,5,2,"[{""name"": ""Will Smith"", ""role_type"": ""Rôle pri..."
19,"Tanguy, le retour ...",https://www.jpbox-office.com/fichfilm.php?id=1...,30 252,1 027 447,Etienne Chatiliez,NaN,France,Comédie,10/04/2019,Tous publics ...,SND,3 902,3 932,NaN,1,6,1,"[{""name"": ""Sabine Azéma"", ""role_type"": ""Rôle p..."

In [37]:
import pandas as pd
import numpy as np

# Charger les fichiers CSV
df_film = pd.read_csv('listfilmjpbox.csv', skipinitialspace=True)  # Fichier principal
df_demarage = pd.read_csv('demarage.csv', skipinitialspace=True)  # Fichier contenant la colonne "Démarrage"


# Remplacer les valeurs manquantes dans "Entrées 1ère Semaine" par les données de "Démarrage"
df_film['Entrées 1ère semaine'] = df_film['Entrées 1ère semaine'].combine_first(df_demarage['Démarrage'])

# Remplir les entrées restantes manquantes avec NaN (cela est déjà fait par défaut)
df_film['Entrées 1ère semaine'] = df_film['Entrées 1ère semaine'].replace('', np.nan)

# Sauvegarder le DataFrame mis à jour dans un nouveau fichier CSV
df_film.to_csv('updated_listfilmjpbox.csv', index=False, quoting=1)  # Quoting pour préserver les guillemets
print("Les données ont été mises à jour et enregistrées dans 'updated_listfilmjpbox.csv'.")

Les données ont été mises à jour et enregistrées dans 'updated_listfilmjpbox.csv'.

In [38]:
demarrage = df_demarage.loc[df["1"] == "Forrest Gump", "Démarrage"]
print(demarrage)

KeyError: '1'

In [6]:
print(df_demarage.loc[df_demarage['Titre'] == 'Underground', 'Démarrage'].iloc[0] if not df_demarage.loc[df_demarage['Titre'] == 'Underground', 'Démarrage'].empty else "Aucun démarrage trouvé pour le titre 'Ali'")

110 060

In [1]:
import pandas as pd

film_df = pd.read_csv('listfilmjpbox.csv', skipinitialspace=True)
demarage_df = pd.read_csv('demarage.csv', skipinitialspace=True)

film_df["Entrées 1ère semaine"] = film_df["Entrées 1ère semaine"].replace("-", pd.NA) 

film_df["Entrées 1ère semaine"] = film_df["Entrées 1ère semaine"].fillna(demarage_df["Démarrage"])

film_df.to_csv("film_with_demarrage.csv", index=False, quoting=1)

In [9]:
print(film_df.columns)
print(demarage_df.columns)

Index(['Titre                                                    ',
       'URL                                                      ',
       'Entrées 1ère semaine', 'Entrées totales',
       'Réalisateur                 ', 'Producteur', 'Pays            ',
       'Genre             ', 'Date de sortie',
       'Classification                                         ',
       'Distributeur               ', 'Rang toutes exploitations',
       'Rang général', 'Rang 2008', 'Nb 1ère places hebdo',
       'Nb semaines Top20', 'Meilleure place hebdo', 'Acteurs'],
      dtype='object')
Index(['Titre', 'Démarrage'], dtype='object')

In [17]:
film_df.columns = film_df.columns.str.strip()


# Sauvegarder le fichier corrigé
film_df.to_csv('film_corrige.csv', index=False) # Supprime les espaces au début et à la fin des colonnes

In [2]:
import pandas as pd

filmmerged_df = pd.merge(film_df, demarage_df, on="Titre", how="left")
filmmerged_df.to_csv("filmmerged.csv", index=False, quoting=1)

if "Démarrage" in filmmerged_df.columns:
    col = filmmerged_df.pop("Démarrage")
    filmmerged_df.insert(2, "Démarrage", col)

filmmerged_df.to_csv("filmmerged.csv", index=False, quoting=1)

NameError: name 'film_df' is not defined

In [13]:
print(demarage_df["Démarrage"].dtypes)

object

In [14]:
demarage_df["Démarrage"] = demarage_df["Démarrage"].astype(str).str.strip().replace("-", None)
demarage_df["Démarrage"] = pd.to_numeric(demarage_df["Démarrage"], errors='coerce')
film_df["Entrées 1ère semaine"] = film_df["Entrées 1ère semaine"].replace("-", pd.NA)
film_df["Entrées 1ère semaine"] = film_df["Entrées 1ère semaine"].fillna(demarage_df["Démarrage"])
film_df.to_csv("film_with_demarrage.csv", index=False, quoting=1)
print(film_df.columns)
print(demarage_df.columns)
print(film_df.head())

Index(['Titre', 'URL', 'Entrées 1ère semaine', 'Entrées totales',
       'Réalisateur', 'Producteur', 'Pays', 'Genre', 'Date de sortie',
       'Classification', 'Distributeur', 'Rang toutes exploitations',
       'Rang général', 'Rang 2008', 'Nb 1ère places hebdo',
       'Nb semaines Top20', 'Meilleure place hebdo', 'Acteurs'],
      dtype='object')
Index(['Titre', 'Démarrage'], dtype='object')
                                               Titre  \
0  Scream 4                                      ...
1  Resident Evil                                 ...
2  Mariages!                                     ...
3  Gainsbourg - (vie héroïque)                   ...
4  L'Homme qui murmurait à l'oreille des chevaux ...

                                                 URL  Entrées 1ère semaine  \
0  https://www.jpbox-office.com/fichfilm.php?id=1...  -
1  https://www.jpbox-office.com/fichfilm.php?id=1...  -
2  https://www.jpbox-office.com/fichfilm.php?id=1...  -
3  https://www.jpbox-office.com/fichfilm.php?id=1...  -
4  https://www.jpbox-office.com/fichfilm.php?id=3...  -

   Entrées totales                   Réalisateur  Producteur  \
0  1 070 890        Wes Craven                           NaN
1  1 105 943        Paul W.S. Anderson                   NaN
2  2 008 899                                 NaN         NaN
3  1 199 451                                 NaN         NaN
4  2 997 201        Robert Redford                       NaN

               Pays               Genre  Date de sortie  \
0  Etats-Unis        Horreur             13/04/2011
1  Etats-Unis        Aventure - Action   03/04/2002
2  France            Comédie             21/04/2004
3  France            Comédie dramatique  20/01/2010
4  Etats-Unis        Romance             02/09/1998

                                      Classification  \
0  Moins de 12 ans                               ...
1  Moins de 12 ans                               ...
2  Distribué par Pan-Européenne                  ...
3  Tous publics                                  ...
4  Tous publics                                  ...

                  Distributeur  Rang toutes exploitations  Rang général  \
0  SND                          3 754                      3 782
1  Metropolitan                 3 641                      3 670
2  Pan-Européenne               1 743                      1 757
3  Universal                    3 331                      3 359
4  GBVI                         869                        871

  Rang 2008  Nb 1ère places hebdo  Nb semaines Top20  Meilleure place hebdo  \
0       NaN                     0                  5  2
1       NaN                     0                  5  2
2       NaN                     1                  7  1
3       NaN                     0                  5  3
4       NaN                     2                  9  1

                                             Acteurs
0  [{"name": "Courteney Cox", "role_type": "Secon...
1  [{"name": "Milla Jovovich", "role_type": "Rôle...
2  [{"name": "Jean Dujardin", "role_type": "Rôle ...
3  [{"name": "Yolande Moreau", "role_type": "Seco...
4  [{"name": "Robert Redford", "role_type": "Rôle...

In [6]:
print(film_df.columns)
print(demarage_df.columns)

Index(['Titre', 'URL', 'Entrées 1ère semaine', 'Entrées totales',
       'Réalisateur', 'Producteur', 'Pays', 'Genre', 'Date de sortie',
       'Classification', 'Distributeur', 'Rang toutes exploitations',
       'Rang général', 'Rang 2008', 'Nb 1ère places hebdo',
       'Nb semaines Top20', 'Meilleure place hebdo', 'Acteurs'],
      dtype='object')
Index(['Titre', 'Démarrage'], dtype='object')

In [16]:
titres_non_corrigés = film_df[~film_df['Titre'].isin(demarage_df['Titre'])]
print("Titres sans correspondance :")
print(titres_non_corrigés['Titre'].tolist())

Titres sans correspondance :

In [5]:
film_df = pd.read_csv("film_corrige.csv", skipinitialspace=True)
demarage_df = pd.read_csv("demarage.csv", skipinitialspace=True)

In [7]:
# Supprimer les espaces superflus et unifier la casse
film_df['Titre'] = film_df['Titre'].str.strip().str.lower()
demarage_df['Titre'] = demarage_df['Titre'].str.strip().str.lower()

In [8]:
filmmerged_df = pd.merge(film_df, demarage_df, on="Titre", how="left")
filmmerged_df.to_csv("filmmerged.csv", index=False, quoting=1)

In [9]:
# Identifier la dernière colonne
last_column = filmmerged_df.columns[-1]

# Extraire la dernière colonne
col = filmmerged_df.pop(last_column)

# Insérer la colonne à la 4ème position (index 3 car l'index commence à 0)
filmmerged_df.insert(3, last_column, col)

# Vérifier le résultat
print(filmmerged_df.head())

                                           Titre  \
0                                       scream 4
1                                  resident evil
2                                      mariages!
3                    gainsbourg - (vie héroïque)
4  l'homme qui murmurait à l'oreille des chevaux

                                                 URL Entrées 1ère semaine  \
0  https://www.jpbox-office.com/fichfilm.php?id=1...                    -
1  https://www.jpbox-office.com/fichfilm.php?id=1...                    -
2  https://www.jpbox-office.com/fichfilm.php?id=1...                    -
3  https://www.jpbox-office.com/fichfilm.php?id=1...                    -
4  https://www.jpbox-office.com/fichfilm.php?id=3...                    -

  Démarrage Entrées totales         Réalisateur  Producteur        Pays  \
0   533 026       1 070 890          Wes Craven         NaN  Etats-Unis
1   533 300       1 105 943  Paul W.S. Anderson         NaN  Etats-Unis
2   533 360       2 008 899                 NaN         NaN      France
3   511 713       1 199 451                 NaN         NaN      France
4   511 833       2 997 201      Robert Redford         NaN  Etats-Unis

                Genre Date de sortie                Classification  \
0             Horreur     13/04/2011               Moins de 12 ans
1   Aventure - Action     03/04/2002               Moins de 12 ans
2             Comédie     21/04/2004  Distribué par Pan-Européenne
3  Comédie dramatique     20/01/2010                  Tous publics
4             Romance     02/09/1998                  Tous publics

     Distributeur Rang toutes exploitations Rang général Rang 2008  \
0             SND                     3 754        3 782       NaN
1    Metropolitan                     3 641        3 670       NaN
2  Pan-Européenne                     1 743        1 757       NaN
3       Universal                     3 331        3 359       NaN
4            GBVI                       869          871       NaN

   Nb 1ère places hebdo  Nb semaines Top20 Meilleure place hebdo  \
0                     0                  5                     2
1                     0                  5                     2
2                     1                  7                     1
3                     0                  5                     3
4                     2                  9                     1

                                             Acteurs
0  [{"name": "Courteney Cox", "role_type": "Secon...
1  [{"name": "Milla Jovovich", "role_type": "Rôle...
2  [{"name": "Jean Dujardin", "role_type": "Rôle ...
3  [{"name": "Yolande Moreau", "role_type": "Seco...
4  [{"name": "Robert Redford", "role_type": "Rôle...

In [12]:
# Supprimer la 3ème colonne (index 2, car les index commencent à 0)
filmmerged_df = filmmerged_df.drop(filmmerged_df.columns[2], axis=1)

# Vérifier le résultat
print(filmmerged_df.head())

                                           Titre  \
0                                       scream 4
1                                  resident evil
2                                      mariages!
3                    gainsbourg - (vie héroïque)
4  l'homme qui murmurait à l'oreille des chevaux

                                                 URL Démarrage  \
0  https://www.jpbox-office.com/fichfilm.php?id=1...   533 026
1  https://www.jpbox-office.com/fichfilm.php?id=1...   533 300
2  https://www.jpbox-office.com/fichfilm.php?id=1...   533 360
3  https://www.jpbox-office.com/fichfilm.php?id=1...   511 713
4  https://www.jpbox-office.com/fichfilm.php?id=3...   511 833

  Entrées totales         Réalisateur  Producteur        Pays  \
0       1 070 890          Wes Craven         NaN  Etats-Unis
1       1 105 943  Paul W.S. Anderson         NaN  Etats-Unis
2       2 008 899                 NaN         NaN      France
3       1 199 451                 NaN         NaN      France
4       2 997 201      Robert Redford         NaN  Etats-Unis

                Genre Date de sortie                Classification  \
0             Horreur     13/04/2011               Moins de 12 ans
1   Aventure - Action     03/04/2002               Moins de 12 ans
2             Comédie     21/04/2004  Distribué par Pan-Européenne
3  Comédie dramatique     20/01/2010                  Tous publics
4             Romance     02/09/1998                  Tous publics

     Distributeur Rang toutes exploitations Rang général Rang 2008  \
0             SND                     3 754        3 782       NaN
1    Metropolitan                     3 641        3 670       NaN
2  Pan-Européenne                     1 743        1 757       NaN
3       Universal                     3 331        3 359       NaN
4            GBVI                       869          871       NaN

   Nb 1ère places hebdo  Nb semaines Top20 Meilleure place hebdo  \
0                     0                  5                     2
1                     0                  5                     2
2                     1                  7                     1
3                     0                  5                     3
4                     2                  9                     1

                                             Acteurs
0  [{"name": "Courteney Cox", "role_type": "Secon...
1  [{"name": "Milla Jovovich", "role_type": "Rôle...
2  [{"name": "Jean Dujardin", "role_type": "Rôle ...
3  [{"name": "Yolande Moreau", "role_type": "Seco...
4  [{"name": "Robert Redford", "role_type": "Rôle...

In [13]:
filmmerged_df.to_csv("filmmerged.csv", index=False, quoting=1)