# nettoyage du dataset

In [1]:
import pandas as pd

In [2]:
df_movies = pd.read_csv("movies_filter_maj.csv")

In [3]:
df_movies.sample(2)

,index,title,image,date,broadcast_place,genres,certificate,synopsis,directors,scenarists,actors,average_notes_press,average_notes_spectators,nationality,distributor,awards,year_production,movie_type,language,entrance_number_fr
1930,2046,Aladdin,https://fr.web.img6.acsta.net/c_310_420/pictur...,22 mai 2019,en salle,"Aventure,Famille,Fantastique",Tout public,Quand un charmant garçon des rues du nom d’Ala...,Guy Ritchie,"John August,Guy Ritchie","Will Smith,Anthony Kavanagh,Mena Massoud","3,2","3,7",U.S.A.,The Walt Disney Company France,1 nomination,2019,Long métrage,Anglais,2 438 526 entrées
4312,4952,OSS 117: Alerte rouge en Afrique noire,https://fr.web.img6.acsta.net/c_310_420/pictur...,4 août 2021,en salle,"Aventure,Comédie,Espionnage",Tout public,"1981. Hubert Bonisseur de La Bath, alias OSS 1...",Nicolas Bedos,Jean-François Halin,"Jean Dujardin,Pierre Niney,Fatou N'Diaye","2,8","2,7",France,Gaumont Distribution,2 nominations,2021,Long métrage,Français,1 619 109 entrées

In [4]:
df_movies['genres'].describe()

count      4879
unique      396
top       Drame
freq       1132
Name: genres, dtype: object

In [6]:
df_movies.shape

(4879, 20)

In [8]:
df_movies['title'] = df_movies['title'].str.lower()

In [11]:
df_movies.sample(2)

,index,title,image,date,broadcast_place,genres,certificate,synopsis,directors,scenarists,actors,average_notes_press,average_notes_spectators,nationality,distributor,awards,year_production,movie_type,language,entrance_number_fr
3436,3789,pearl,https://fr.web.img3.acsta.net/c_310_420/pictur...,30 janvier 2019,en salle,Drame,Tout public,Léa Pearl s’apprête à concourir pour le presti...,Elsa Amiel,Elsa Amiel,"Julia Föry,Peter Mullan,Vidal Arzoni","3,3","3,2","France,Suisse",Haut et Court,Aucun,2018,Long métrage,"Anglais, Français",3 129 entrées
2428,2577,la troisième guerre,https://fr.web.img3.acsta.net/c_310_420/pictur...,22 septembre 2021,en salle,Drame,Tout public,Léo vient juste de terminer ses classes et pou...,Giovanni Aloi,"Giovanni Aloi,Dominique Baumard","Anthony Bajon,Karim Leklou,Leïla Bekhti","3,3","2,6",France,Capricci Films,1 nomination,2019,Long métrage,Français,11 317 entrées

In [12]:
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4879 entries, 0 to 4878
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   index                     4879 non-null   int64
 1   title                     4879 non-null   object
 2   image                     4879 non-null   object
 3   date                      4879 non-null   object
 4   broadcast_place           4879 non-null   object
 5   genres                    4879 non-null   object
 6   certificate               4879 non-null   object
 7   synopsis                  4879 non-null   object
 8   directors                 4879 non-null   object
 9   scenarists                4879 non-null   object
 10  actors                    4858 non-null   object
 11  average_notes_press       4879 non-null   object
 12  average_notes_spectators  4879 non-null   object
 13  nationality               4879 non-null   object
 14  distributor               4878 non-null   object
 15  awards                    4879 non-null   object
 16  year_production           4879 non-null   int64
 17  movie_type                4879 non-null   object
 18  language                  4879 non-null   object
 19  entrance_number_fr        4879 non-null   object
dtypes: int64(2), object(18)
memory usage: 762.5+ KB

In [15]:
df_movies['average_notes_press'] = df_movies['average_notes_press'].str.replace(",", ".")

In [16]:
df_movies['average_notes_press']

0       4.6
1       2.8
2       3.9
3       3.7
4       3.0
       ...
4874    3.6
4875    3.5
4876    3.1
4877    2.9
4878    3.7
Name: average_notes_press, Length: 4879, dtype: object

In [17]:
df_movies['average_notes_press'] = df_movies['average_notes_press'].astype('float')

In [20]:
df_movies['average_notes_spectators'] = df_movies['average_notes_spectators'].str.replace(",", ".")
df_movies['average_notes_spectators']

0       4.1
1       1.9
2       4.1
3       3.8
4       3.1
       ...
4874    2.8
4875    2.1
4876    2.4
4877    2.3
4878    3.4
Name: average_notes_spectators, Length: 4879, dtype: object

In [21]:
df_movies['average_notes_spectators'] = df_movies['average_notes_spectators'].astype('float')

ValueError: could not convert string to float: '--'